theme: jekyll-theme-minimal
title: XYS's Static Publish
description: This Document/Page is generated automatically via Ruby, Jekyll
show_downloads: false
markdown: kramdown
kramdown:
    math_engine: katex